const CHECKPOINT_TYPE = {
  QUIZ: "QUIZ",
  TASK: "TASK",
};

const LESSON_ELEMENT_TYPE = {
  IMG: "IMG",
  VIDEO: "VIDEO",
  HTML_STR: "HTML_STR",
};

module.exports = { CHECKPOINT_TYPE, LESSON_ELEMENT_TYPE };
