const CHECKPOINT_TYPE = {
  QUIZ: "QUIZ",
  TASK: "TASK",
};

const LESSON_ELEMENT_TYPE = {
  IMG: "IMG",
  VIDEO: "VIDEO",
  RICH_TEXT: "RICH_TEXT",
};

const USER_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  TEACHER: "TEACHER",
  LEARNER: "LEARNER",
};

module.exports = { CHECKPOINT_TYPE, LESSON_ELEMENT_TYPE, USER_ROLES };
